export const GET_PHOTOS_REQUEST = 'GET_PHOTOS_REQUEST';
export const GET_PHOTOS_SUCCESS = 'GET_PHOTOS_SUCCESS';
export const GET_PHOTOS_FAILURE = 'GET_PHOTOS_FAILURE';

export const CHANGE_ORDER_MODE = 'CHANGE_ORDER_MODE';
export const CHANGE_VIEW_MODE = 'CHANGE_VIEW_MODE';

export const OPEN_FULLSCREEN = 'OPEN_FULLSCREEN';
export const CLOSE_FULLSCREEN = 'CLOSE_FULLSCREEN';

